### ISSUE TITLE
Move to node 14 as minimum engine version

### ISSUE THREAD

**Issue by makepanic** [piobyte/flamingo#44]
With 14 becoming the next active LTS release on 2020-10-27, use it as the minimum node engine version.

See https://nodejs.org/en/about/releases/

**Comment by bayucakra20** [comment]
Hi, I'd would like to work on this issue

**Comment by makepanic** [comment]
Sure feel free to open a PR which adjusts the engine version.

Do you want hints on what should change?

**Comment by bayucakra20** [comment]
I added the `engines` field inside of package.json isn't it? or sure you can share the hints what should change
